### PR TITLE
Add Laravel authentication scaffolding flag

### PR DESCRIPTION
**Pull request by milose**
Added -a and --auth flags to use Artisan for scaffolding authentication routes and views upon project creation.

screen shot 2016-09-23 at 09 20 36

### CODE REVIEW

**Comment by milose** [comment]
Oh I could add `yarn` into this as well 🎱

**Comment by Xantios** [comment]
Maybe migrate it to? :)

**Comment by milose** [comment]
@Xantios Hmm, migrate is probably an issue, since you might want to modify User model before migrating.

**Comment by mattstauffer** [comment]
Fantastic-- thanks @milose !

**Comment by milose** [comment]
@mattstauffer should we run yarn if exist, if not run npm install by default? I could make that happen in a jiffy 🖌

**Comment by mattstauffer** [comment]
@milose I'm 99% down with the idea of yarn or npm after auth. I feel like there's a reason not to do it but can't think of the reason...

**Comment by milose** [comment]
Yeah, unless people are **not** using elixir. I am going to make a pull request, so we can discuss it there.

**Pull request merged**
