### PR TITLE
Add feature to set path and commit message

### PR DESCRIPTION
**Pull request by josebailo**
With argument -p or --path can specify the base path where create the
application. Current path by default.

With argument -m or --message can specify the first commit message. "Initial
commit." by default.

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks Jose! I want to think about this for a second. I'm very much interested in keeping the syntax and the code  as clean and simple as possible. But I see this PR and I'm thinking about it. thanks for your time!

**Comment by josebailo** [comment]
You're welcome!

I tried to keep it simple and clean. In fact you can use the script without arguments and works in the same way :)

**Comment by mattstauffer** [comment]
@josebailo You totally did! If you had made it required, I would've just rejected it. :)

And the features are all flag features, so this won't have a negative impact on the usability for a new user. You did a great job.

I think I just don't like the idea of this having the *need* for flags--it's really a stupid little command that just saves a little bit of mental space, but it's all about moving super fast.

I'm trying to figure out how I feel about the idea of having to think about flags when you're using it. It's about how much is it "opinionated default that you can override" and how much it's "it's this way or use another tool."

Will keep thinking. Again, thanks Jose.:)

**Comment by mattstauffer** [comment]
@josebailo merged--thanks so much for your help!

**Pull request merged**
