### PR TITLE
Changed .env replacements to use perl instead of sed

### PR DESCRIPTION
**Pull request by philip**
This replaces sed usage with perl -pie.

My macOS system has GNU sed so the Darwin check did not work for me. Rather than rewrite the sed checks, I simply replaced sed with perl as perl just works.

It might require tweaking as I'm not an expert here, but I did test this `lambo` on macOS and the .env replacement code on Ubuntu.

In addition, it changes the current values and does not assume the current defaults (e.g., homestead, secret, localhost) in case those change or if lambo is executed on an existing project. This is a BC break that could be removed, if needed, as it might offer unattended consequences.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@philip Thanks! I'll try to get a few folks to check this out and then we'll merge.

**Comment by mattstauffer** [comment]
@philip Sorry for the delay. I don't know Perl, so I've put out a tweet about it.

https://twitter.com/stauffermatt/status/931542712511234048

**Comment by divspace** [comment]
I would give this a thumbs down (mainly because we can't have the sed separators set to `/` since the `APP_URL` will contain multiple, so switch it out with `|` or `@` or something else. Give this a shot instead:

```bash
#!/usr/bin/env bash

UNAMEOUT="$(uname -s)"

case "${UNAMEOUT}" in
    Linux*)     MACHINE=linux;;
    Darwin*)    MACHINE=mac;;
    *)          MACHINE="unknown"
esac

if [ "$MACHINE" == "unknown" ]; then
    echo "Unsupported system type!"
    exit 1
fi

if [ "$MACHINE" == "linux" ]; then
    SEDCMD="sed -i"
elif [ "$MACHINE" == "mac" ]; then
    SEDCMD="sed -i .bak"
fi

## Set up colors
red=$(tput setaf 1)
green=$(tput setaf 2)
orange=$(tput setaf 3)
reset=$(tput sgr0)

## Init functions
showhelp()
{
    echo " "
    echo "${green}Lambo: Super-powered '${orange}laravel new${green}' for Laravel and Valet"
    echo "${reset}________________________________________________________"
    echo " "
    echo "${orange}Usage:"
    echo "${reset}  lambo myApplication [arguments]"
    echo " "
    echo "${orange}Options:"
    echo "${green}  -h, --help${reset}                 Show brief help"
    echo "${green}  -e, --editor EDITOR${reset}        Specify an editor to run '${green}EDITOR .${reset}' with after"
    echo "${green}  -m, --message \"message\"${reset}    Customize the initial commit message"
    echo "${green}  -p, --path PATH${reset}            Customize the path in which the new project will be created"
    echo "${green}  -d, --dev${reset}                  Use Composer to install on the develop branch"
    echo "${green}  -a, --auth${reset}                 Use Artisan to scaffold all of the routes and views you need for authentication"
    echo "${green}  -n, --node${reset}                 Runs '${green}yarn${reset}' if installed, otherwise runs '${green}npm install${reset}' after creating the project"
    quit
}

abort()
{
    echo >&2 '
***********************************************
*** There was an error running this script. ***
***********************************************
'
    echo "An error occurred. Exiting..." >&2
    exit 1
}

quit()
{
    trap : 0
    exit 0
}

## Set up error handling
trap 'abort' 0

## Start script

PROJECTNAME=$1
PROJECTPATH="."
MESSAGE="Initial commit."
DEVELOP=false
AUTH=false
NODE=false
EDITOR=""
TLD=$(php -r "echo json_decode(file_get_contents('$HOME/.valet/config.json'))->domain;")

### Check for project name argument; if none passed, show help
if [[ $# -eq 0 ]]; then
    showhelp
fi

### Handle arguments
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -h|--help)
            showhelp
            ;;
        -p|--path)
            PROJECTPATH="$2"
            shift
            ;;
        -m|--message)
            MESSAGE="$2"
            shift
            ;;
        -e|--editor)
            EDITOR="$2"
            shift
            ;;
        -d|--develop|--dev)
            DEVELOP=true
            ;;
        -a|--auth)
            AUTH=true
            ;;
        -n|--node)
            NODE=true
            ;;
        *)
            ;;
    esac

    shift
done

echo "
***********************************************
Creating new Laravel app ${green}$PROJECTNAME${reset}
***********************************************
"

cd "$PROJECTPATH" || exit

if [[ "$DEVELOP" = true ]]; then
    laravel new "$PROJECTNAME" --dev
else
    laravel new "$PROJECTNAME"
fi

cd "$PROJECTNAME" || exit

if [[ "$NODE" = true ]]; then
    # check if yarn is executable, otherwise use npm
    if hash yarn 2>/dev/null; then
        yarn
    else
        npm install
    fi
fi

if [[ "$AUTH" = true ]]; then
    php artisan make:auth
fi

git init
git add .
git commit -m "$MESSAGE"

if [[ "$EDITOR" != "" ]]; then
    $EDITOR .
fi

# Update .env to point to this database with `root` username and blank pw,
# like Mac MySQL defaults, and appropriate domain
PROJECTURL="http://$PROJECTNAME.$TLD"

$SEDCMD "s|APP_URL=.*|APP_URL=$PROJECTURL|g" .env
$SEDCMD "s|DB_DATABASE=.*|DB_DATABASE=$PROJECTNAME|g" .env
$SEDCMD "s|DB_USERNAME=.*|DB_USERNAME=root|g" .env
$SEDCMD "s|DB_PASSWORD=.*|DB_PASSWORD=|g" .env

if [ -f .env.bak ]; then
    rm .env.bak
fi

if [[ "$MACHINE" == "mac" ]]; then
    open "$PROJECTURL"
elif [[ "$MACHINE" == "linux" ]]; then
    xdg-open "$PROJECTURL"
fi

case $PROJECTPATH in
 ".") prettyPath="$PROJECTNAME" ;;
 *) prettyPath="$PROJECTPATH/$PROJECTNAME" ;;
esac

if [[ "$SHELL" != "" ]]; then
    exec "$SHELL"

    echo "

    ***********************************************

    You're ready to go!"
else
    echo "

    ***********************************************

    You're ready to go! Remember to cd into '${green}$prettyPath${reset}' before you start editing."
fi

# End script; disable error handling
trap : 0
```

**Comment by mattstauffer** [comment]
@divspace Thanks for taking a look.

However, this PR is replacing a functioning `sed` with `perl`, so my request was for folks to review the Perl implementation, not the old sed version. Is that something you can help with? Thanks!

**Comment by icawebdesign** [comment]
It looks good Matt.

I tested this on a Laravel 5.5 .env file I pulled out of a recent project (with changes from the default) and didn't encounter any issues.

Not written Perl for a while, but have done a fair bit over the years (starting back 16 or so years ago).

**Comment by divspace** [comment]
Ah, my mistake on not understanding. Will update with pure Perl shortly.

**Comment by mattstauffer** [comment]
@icawebdesign thanks!!

**Comment by unixbigot** [comment]
Long time perlwrchere responding to your tweet.

The change will work.  You could save some forks by doing perl -pi -e sub1 -e sub2 -e sub3 etc.  That is, looping over your commands to build a single perk invocation rather than many.

**Comment by mattstauffer** [comment]
@unixbigot Thanks for the review!

**Comment by mattstauffer** [comment]
@philip Thank you so much for this contribution!

**Pull request merged**
