### PR TITLE
Run `npm install` or `yarn` on the project.

### PR DESCRIPTION
**Pull request by milose**
This runs by default. It first tries to see if `yarn` is installed, and runs it. Otherwise, it will run `npm install`

### CODE REVIEW

**Comment by mattstauffer** [comment]
So i just realized.. this is gonna slow the everloving crap out of it for anyone not using Yarn. Need to think about whether we want that.. because I'll most commonly start coding BEFORE I run npm install so I can be up and running while it takes fifteen hours.

**Comment by milose** [comment]
Agreed. So should we add an option, instead?
```
-n --npm Runs yarn if installed, otherwise runs npm install after creating the project.
```

**Comment by mattstauffer** [comment]
:+1: I like that.

**Comment by milose** [comment]
There we go. 🎉

**Comment by mattstauffer** [comment]
<3 thanks!!

**Pull request merged**
