### PR TITLE
Update .env to point to local .dev domain

### PR DESCRIPTION
**Pull request by burakerdem**

### CODE REVIEW

**Comment by mattstauffer** [comment]
Hm. Problem with this is that not everyone uses `.dev` on Valet. Not sure if there's a good way to get around that...

**Comment by benswinburne** [comment]
Something like this would work.

    VALETDOMAIN=$(php -r 'echo json_decode(file_get_contents("$_SERVER['HOME']/.valet/config.json"))->domain;')

    sed -i '' "/APP_URL/s/localhost/$PROJECTNAME\.$VALETDOMAIN/" .env

**Comment by mattstauffer** [comment]
Ha, it's funny you mention that: we just wrote almost that same code earlier today elsewhere in the project. Will update it here. 

Sent from Outlook for iOS




On Tue, Aug 16, 2016 at 6:20 PM -0400, "Ben Swinburne" <notifications@github.com> wrote:












Something like this would work.

VALETDOMAIN=$(php -r 'echo json_decode(file_get_contents("$_SERVER['HOME']/.valet/config.json"))->domain;')

sed -i '' "/APP_URL/s/localhost/$PROJECTNAME\.$VALETDOMAIN/" .env

**Comment by mattstauffer** [comment]
@burakerdem Thanks!!

**Pull request merged**
