### PR TITLE
add option to create a new database for the project

### PR DESCRIPTION
**Pull request by muhammetsait**
Same as #54 but added command line flag + updated readme file

Changes
===
 - `--create-db` flag to create new mysql db for the project.
 - Database name now always replaces dashes (`-`) with underscores (`_`). Even if the database is created manually this still applies.
 - documented three flags in readme: `create-db`, `dbuser`, and `dbpassword`.
 - added a 'figlet' to the help message for extra swag

### CODE REVIEW

**Comment by mattstauffer** [comment]
@muhammetsait Can you re-make this, but do it in a way that keeps the original commits @ijpatricio added in his branch so he can get credit for his original work? Then I'd love to merge.

Thank you!

**Comment by muhammetsait** [comment]
I didn't know this was possible (to edit on pull request submitted by another person?). I am not sure if I did it correctly? Is there a better way or a recommended way?

**Comment by mattstauffer** [comment]
image

There are a few ways to do it, but I see both of your names here, so it looks good to me! :) I'll review the PR now.

**Comment by ijpatricio** [comment]
> @muhammetsait Can you re-make this, but do it in a way that keeps the original commits @ijpatricio added in his branch so he can get credit for his original work? Then I'd love to merge.
> 
> Thank you!

Thank you @mattstauffer ❤️❤️❤️

Incredible, the amount of care you put into everything you do, and the appreciation you have towards every individual, no matter what. Both online and live, as we've met in laracon us nyc 2017!

Only if 1% of the world would be more like you, it would be a much more amazing place to live in! :)

Cheers!

**Pull request merged**
